### ISSUE TITLE
Что будет выведено в консоль: Числа: 1

### ISSUE THREAD

**Issue by kicumkicum** [apoluektova/js-labs#6]
В комментарии написать, что будет выведено в консоль, не вызывая кода. Не обязательно отвечать на все сразу. Ответ в виде:
```md
1: 42
2: 43
```

Вопрос:

```js
// 1.
let a = null + undefined;
console.log(a);

// 2.
a = 13 + undefined;
console.log(a);

// 3.
a = 13 + null;
console.log(a);

// 4.
a = 100/0;
console.log(a);

// 5.
a = 100 * 'aaa';
console.log(a);

// 6.
a = Math.sqrt(-4);
console.log(a);
```

**Comment by apoluektova** [comment]
1. NaN
2. NaN
3. 13
4. infinity
5. NaN
6. NaN

**Comment by kicumkicum** [comment]
Номер 3 для меня стал откровением. Попробуй в консоли другие арифметические операции с `null`

**Comment by apoluektova** [comment]
Статья про преобразование типов - https://learn.javascript.ru/type-conversions

**Comment by kicumkicum** [comment]
Ты отлично справилась! Задачу закрываю, как решенную. Посмотреть решенные задачи можно в закрытых ишью
