### ISSUE TITLE
Что будет выведено в консоль: Числа: 2

### ISSUE THREAD

**Issue by kicumkicum** [apoluektova/js-labs#7]
Тут задача с подвохом и очевидный ответ нужно сразу отбросить.

```js
let a = (1,5 - 1) * 2;

console.log(a);
```

**Comment by apoluektova** [comment]
Думаю, будет 8

**Comment by kicumkicum** [comment]
Это правильный ответ. Молодец!
Расскажи, как ты размышляла

**Comment by apoluektova** [comment]
Я прочитала про оператор запятая, узнала, что вернется результат только последнего из выражений, разделенных запятой - в этом примере это 5-1. Статья тут - https://learn.javascript.ru/operators

**Comment by kicumkicum** [comment]
Отлично
