### ISSUE TITLE
Что будет выведено в консоль: Объекты: 1

### ISSUE THREAD

**Issue by kicumkicum** [apoluektova/js-labs#8]
```js
var a={},
    b={key:'b'},
    c={key:'c'};

a[b]=1;
a[c]=2;

console.log(a[b]);
```

**Comment by apoluektova** [comment]
Есть пустой объект а. Когда пишем a[b]=1, то кладем в него свойство с ключом b и значением 1. Но b это объект, а ключами могут быть только строки, поэтому в результате приведения в виде ключа b мы получаем [object Object]. 
Таким образом объект а на данный момент выглядит как  a= { '[object Object]': 1}.
В строке a[c]=2 происходит то же самое. Только получается, что мы обращаемся к уже существующему ключу [object Object] и записываем туда значение 2. Так что в консоль логе в итоге будет 2.

**Comment by kicumkicum** [comment]
Отличное объяснение и ответ абсолютно правильный!
