### ISSUE TITLE
Что будет выведено в консоль: Объекты: 2

### ISSUE THREAD

**Issue by kicumkicum** [apoluektova/js-labs#9]
```js
var o = {
    name: 'Jony',
    getName: function() {
        console.log(this.name);
    }
}

// 1.
o.getName();

var getName = o.getName;
// 2.
getName();
```

**Comment by apoluektova** [comment]
1. 'Jony'
2. Не уверена, что понимаю, что здесь происходит. В переменную getName мы положили функцию из объекта o, а потом ее вызываем. В этом случае this будет ссылаться на window, а this.name в консоль.логе будет undefined, других вариантов у меня нет.

**Comment by kicumkicum** [comment]
Ты всё правильно написала, молодец!

А как можно сохранить контекст во втором случае?

**Comment by apoluektova** [comment]
Можно либо сделать так var getName = o.getName.bind(o), либо так getName.call(o);

**Comment by kicumkicum** [comment]
Напиши ещё третий вариант и закрываем

**Comment by apoluektova** [comment]
getName.apply(o);

**Comment by kicumkicum** [comment]
Всё верно!
